# Site settings
title: llmswap
description: Universal AI CLI - 8 Providers, One Interface
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://llmswap.org" # the base hostname & protocol for your site
repository: sreenathmmenon/llmswap

# Build settings
remote_theme: just-the-docs/just-the-docs
color_scheme: llmswap
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Aux links for the upper right navigation
aux_links:
  "GitHub":
    - "//github.com/sreenathmmenon/llmswap"
  "PyPI":
    - "//pypi.org/project/llmswap"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Footer content
footer_content: "Copyright &copy; 2025 llmswap. Distributed under the <a href=\"https://github.com/sreenathmmenon/llmswap/blob/main/LICENSE\">MIT license.</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Google Analytics
ga_tracking: # Add your GA tracking ID here

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections for documentation sections
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
  tutorials:
    permalink: "/:collection/:path/"
    output: true

# Collection defaults
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"
      nav_order: 1
  - scope:
      path: ""
      type: "tutorials"
    values:
      layout: "default"
      nav_order: 2

# Callouts
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  important:
    title: Important
    color: yellow
  tip:
    title: Pro Tip
    color: green

# Code highlighting
highlighter: rouge
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Exclude from build
exclude:
  - SITE_PLAN.md
  - FEATURES_COMPLETE.md
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/